### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#12]
Add jsZgb logo as favicon to our site

![img](https://avatars3.githubusercontent.com/u/5462955?v=3&s=200)

**Comment by dinodsaurus** [comment]
I think its not solved, because I dont see it in chrome:( , tried in normal mode and also in icognito. On safari and firefox works fine (but maybe its my cache), so if it works for others we can close it :+1:

**Comment by shime** [comment]
works for me :+1:
