### ISSUE TITLE
Javascript generators

### ISSUE THREAD

**Issue by mieszko4** [jszgb/jszgb.github.io#14]
Idea of presentation about different ways of handling asynchronous programming in es6: callbacks, Promises, generator/yield, async/wait (maybe just mention since it is in es7).

Then extending on generators with coroutines: data producers + data consumers => coroutines

Reference: http://exploringjs.com/es6/ch_generators.html

**Comment by dinodsaurus** [comment]
I think @lblazecki gave a talk about this, so I can close it ;)
