### ISSUE TITLE
ES6 & ES7

### ISSUE THREAD

**Issue by mieszko4** [jszgb/jszgb.github.io#15]
Quick summary of new features of es6. Examples of how something is done in es5 and how can it be done in es6, i.e. how es6 solves some of es5 problems.

Depending on time more details on some of the features like:
- module import/export
- WeakMap/WeakSet
- template literals (e.g. https://github.com/lukehoban/es6features/issues/49#issuecomment-146866137)
- pattern matching and default parameters
- rest/spread operator (e.g unique values in array using Set)
- codepoints and RegExp in unicode
- iterator and generator function - without too much details of asynch programming (e.g. Fibonacci) 
- class and inheritance

There are also other cool features like Symbols and Meta-programming but I guess it is a bit too much for the first presentation on es6 :)

Reference: https://github.com/lukehoban/es6features
Reference: http://es6-features.org/#Constants
Reference: http://exploringjs.com/es6/

**Comment by silvenon** [comment]
Me and Luka can take this one :+1: A great excuse to learn some features I don't know about yet.

**Comment by dinodsaurus** [comment]
@lblazecki :100:
