### ISSUE TITLE
Slides history

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#17]
Go trough [meetup.com ](http://www.meetup.com/JavaScript-Zagreb/) history and collect all the presentation(slides) from meetups that were held in past and input them to our `slides/slides.md` file

**Comment by silvenon** [comment]
Nodeschool too?

**Comment by dinodsaurus** [comment]
nop

**Comment by silvenon** [comment]
[You linked](http://www.meetup.com/JavaScript-Zagreb/events/221413790/) your browserify + React repo there, but I don't see you in the description. Did you have a spontaneous presentation? What is a short description of your talk?

**Comment by dinodsaurus** [comment]
Yea, it was kinda lightning talk, introduction to react and ES6 ;)
