### ISSUE TITLE
Make jsZgb logo a hexagon

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#18]
Take our `logo.svg`and make a hexagon from it

**Comment by zappan** [comment]
@dinodsaurus why?

**Comment by retro** [comment]
No!

**Comment by dinodsaurus** [comment]
I know this is your baby @retro, we will use the current one for almost everything but I would like to follow [hipster](http://hexb.in/) trends and also have a jsZgb logo as a haxagon (we were planing to do some sticker printing and nodeschool zgb logo is a hexagon so it would be a better match)
![nodeschool zagreb](https://github.com/nodeschool/zagreb/raw/master/zagreb.png)
