### ISSUE TITLE
Introduction to Electron

### ISSUE THREAD

**Issue by Vj3k0** [jszgb/jszgb.github.io#19]
Electron enables you to create cross-platform desktop apps with web technologies. It is based on Chromium and uses Node.js to enable working with OS, and HTML, CSS and JavaScript for UI.

Presentation would contain:
- introduction
- list good and bad sides
- comparison with similar solutions
- demo and quick overview
- (extra) tips and tricks

For years I've been working as an ActionScript developer making cross-platform apps in Adobe AIR. Few months ago I've started to work with Electron. I'm also writing my thoughts and findings on my blog [Electron Rocks!](http://electron.rocks)

**Comment by dinodsaurus** [comment]
Thanks a lot and nice job with your blog!

**Comment by dinodsaurus** [comment]
Može ova prezentacija za tjedan dana? @Vj3k0

**Comment by Vj3k0** [comment]
@dinodsaurus Moze!

**Comment by dinodsaurus** [comment]
Odlicno, cini mi se da bi ovo mogli razdvojiti u vise predavanja?
Tipa `intro`,`intermediate`, `deploy`
Ima to smisla ?

**Comment by Vj3k0** [comment]
Mogao bi podjeliti u seriju predavanja. U principu ove sve stvari koje sam izlistao mogu biti introduction ( s time da ne pokazujem detaljno kod u demou i tips and tricks ostavim kao ekstra).
Jedno predavanje bi mogao napravit live session da u principu napravim demo aplikaciju i objasnim detaljnije kod. A dodatno bi mogao jos napravit i prezentaciju o deployu (no trenutno jos radim na tome da izbrusim kakav deploy actually valja).

P.S. Updateao sam originalni comment gore.
