### ISSUE TITLE
NodeSchool International Day 21st May

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#22]
#### Saturday 21st May 2016
- [x] Pick location
- [x] Find 5 core people
- [x] Print NodeSchool Zagreb stickers
- [x] Print Posters for the event
- [x] Decide on number of participants
- [x] Create sign up page earlier (maybe already May 1st?)
- [x] Find sponsor for drinks and snacks
- [x] Find marketing partners to spread the word (mailinglist, facebook, twitter etc.)
- [x] Find enough mentors (depends on number of participants)
- [x] Redesign our page - http://nodeschool.io/zagreb/
#### Additionally see:

https://github.com/nodeschool/international-day/blob/2016/PARTICIPATING.md
https://github.com/nodeschool/international-day

**Comment by dinodsaurus** [comment]
Our sponsor/partner for this event will be Five - http://five.agency

**Comment by dinodsaurus** [comment]
New design is here!!!!
If someone is willing to slice it, he is more then welcome :)
https://www.dropbox.com/s/q69fyu1tnnug1si/nodeschool.jpg?dl=0

**Comment by vblazenka** [comment]
@dinodsaurus  ako ti se niko ne ponudi mogu ja iskodirati to :)

**Comment by dinodsaurus** [comment]
Wohoooo we are good to go!!!
