### ISSUE TITLE
Down with jQuery

### ISSUE THREAD

**Issue by silvenon** [jszgb/jszgb.github.io#25]
I would like to convince people that they (probably) don’t need jQuery (anymore).

**Comment by mkdizajn** [comment]
I'm +1 this!

**Comment by silvenon** [comment]
@dinodsaurus I would like to do this presentation in the next meetup.

## You (probably) don't need jQuery (anymore)

There was a time when browsers were handling DOM, AJAX etc. very differently. Normalizing these manually was a pain, so libraries like jQuery were invaluable. Now that browsers have more-or-less agreed upon these things and frameworks have started to rise, jQuery has become an unnecessary abstraction and might be preventing you from getting better at JavaScript. I will show you how to achieve common tasks without it, so you can decide whether you really need it.

**Comment by dinodsaurus** [comment]
Awesome!
