### ISSUE TITLE
Service Workers

### ISSUE THREAD

**Issue by teodragovic** [jszgb/jszgb.github.io#31]
Hi. I would like to propose talk about Service Workers. Talk would cover the what of Service Workers, their prerequisites and how can we use SW to make websites available offline, control network conditions and create conditional actions depending on requests our website makes (+ some bonus features).

Talk would be given in Croatian. Duration TBD.

**Comment by dinodsaurus** [comment]
Awesome! 
We are full for this month and we will have a summer break.. but we will continue in September so we will keep in touch ;)

**Comment by dinodsaurus** [comment]
Hey @teodragovic are you still interested to give a talk about service workers ?

**Comment by teodragovic** [comment]
Yes, but I can't do it before december. Do you have some dates in mind?
