### ISSUE TITLE
Drinkup over summer

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#32]
When should we organize a drinkup this summer?
So we can meet before next session of meetup starts :)

**Comment by lblazecki** [comment]
Maybe to ask it on meetup page?

**Comment by perpaer** [comment]
Maybe we should make a poll in which people could vote on a certain week which is most suitable to them; then after the poll, decide on which day/date. 
Just my two cents.

**Comment by HBalija** [comment]
If we are aiming for a "proper" drinkup, I vote for a Friday or Saturday. Mid July maybe... Otherwise it will be a coffee.js :)

Hrvoje

**Comment by dinodsaurus** [comment]
I would say proper drinkup 🍻

**Comment by shime** [comment]
Apparently not happening 😄
