### ISSUE TITLE
Talk proposal: Why I stopped using CoffeeScript

### ISSUE THREAD

**Issue by elkarrde** [jszgb/jszgb.github.io#33]
Hi! I'd like to propose a talk titled **Why I stopped using CoffeeScript**.

As much of you know, I've been using CoffeeSscript for better part of four years, and now I've stooped using it in favour of pure, plain vanilla JavaScript, not even fancy-pants ES6. I'd like to share my experience with CoffeeScript, and the reasons why I'm no longer using it.

Talk would be in Croatian, timed for shorter time-slot - no examples and working demos needed.

**Comment by lblazecki** [comment]
Hello @elkarrde 

This seams as an interesting and fun talk :)
I share your idea that ES6 in now taking over.

What is your proposed time length for the talk?
Can you post your slides here?

**Comment by elkarrde** [comment]
@lblazecki I should be able to fit in shorter time-slot - that's 20-ish minutes, or something like it, isn't it?

I have no definitive slides yet, just general ideas, so I'm flexible with timing.

**Comment by lblazecki** [comment]
@elkarrde that's great time length.
I have added you to https://github.com/jszgb/jszgb.github.io/blob/master/slides/upcoming.md

We could do this talk in September or in October.
Can you provide slides in next few weeks?

**Comment by elkarrde** [comment]
@lblazecki that's great, thanks!

Sure, I'll crunch down those slides asap, and let you know when I'm done - next week, probably.

**Comment by dinodsaurus** [comment]
@elkarrde Can you have this presentation this month? (21.9)

**Comment by elkarrde** [comment]
@dinodsaurus Sure, no problem.

**Comment by dinodsaurus** [comment]
@elkarrde Could you just give me your email so I can send you your free ticket for webcamp :)

**Comment by elkarrde** [comment]
@dinodsaurus Yippie! It's nfalica@gmail.com.
Also, the talk is up and running: http://bit.ly/2ddB7jj
Also, on Github: https://github.com/elkarrde/jszg-whyistoppedusingcoffeescript
