### ISSUE TITLE
React Storybook

### ISSUE THREAD

**Issue by dinkom** [jszgb/jszgb.github.io#35]
Hi! I would like to propose a talk about building and testing React components with the help of React Storybook: https://github.com/kadirahq/react-storybook and some test libraries that play along nicely.

The talk would be 15-20 minutes and would include some live examples and perhaps a bit of coding (which always goes terribly wrong, but let's risk it). It could be either in Croatian or in English, depending on who comes to the meetup.

**Comment by lblazecki** [comment]
Hi @dinkom 

This looks like an interesting topic! 
20 min is ideal time for presentation (with live coding).
You can prepare slides in English and we can see then on a day of the meetup if there is a need to speak in English or Croatian is ok.

What do you think, could a presentation be ready for next meetup?

**Comment by dinkom** [comment]
Sure, it can be ready. Do we even have a meetup next month due to WebCamp?

**Comment by lblazecki** [comment]
Yes. WebCamp is on 28/29 of October and meetup should be on 19 of October.

**Comment by dinodsaurus** [comment]
Can we move this for the next month @dinkom ?

**Comment by dinkom** [comment]
Sure, I was just about to ask.

**Comment by dinkom** [comment]
Wasn't I supposed to give a talk this month?

**Comment by vblazenka** [comment]
If you guys want you can postpone my talk for December. I didn't even open the issue for my talk. I think that it would be fair that dinkom gives his talk first.

**Comment by dinodsaurus** [comment]
Heeey.. sorry for this it is my mistake...
thanks @wedranb 👍  so @dinkom if you want you can do it this month. Just send me the details and I will replace the text on meetup.com

**Comment by dinkom** [comment]
I can go next time (so we don't confuse the people who already read the announcement), it's not a problem at all - just don't forget me next month 😄  @dinodsaurus @lblazecki @wedranb

**Comment by lblazecki** [comment]
sure :)

**Comment by lblazecki** [comment]
@dinkom 
Can you please create a short intro that we will put on JS meetup page

**Comment by lblazecki** [comment]
@dinkom

**Comment by silvenon** [comment]
Can't wait for this talk, I'd love to hear about this. 👍

**Comment by silvenon** [comment]
@lblazecki should this be closed?
