### ISSUE TITLE
Serverless

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#36]
Someone should talk about serverless https://serverless.com/

**Comment by gajo4256** [comment]
maybe we could also evaluate and show https://github.com/claudiajs

**Comment by dinodsaurus** [comment]
Wohooo :1st_place_medal:
So @gajo4256 will do a presentation about that in May

**Comment by dinodsaurus** [comment]
@gajo4256 wanna talk this month?

**Comment by gajo4256** [comment]
hi @dinodsaurus, I'm a little tight with the time, but if there aren't any other candidates I will try to prepare it. Could you let me know until the end of the day if there is anybody for Wednesday? If not, count me in, I will do it somehow.

Thnx

**Comment by gajo4256** [comment]
@dinodsaurus I will send you my talk desc sometime this evening. Count me in for Wednesday.

Gajo

**Comment by dinodsaurus** [comment]
Thanks a lot, sounds awesome!!!
