### ISSUE TITLE
Presentation proposal: How to write your own Yeoman generator

### ISSUE THREAD

**Issue by slavede** [jszgb/jszgb.github.io#37]
Hi guys, I've already reported a presentation which I would give here https://github.com/jszgb/jszgb.github.io/blob/master/slides/upcoming.md. "How to write your own Yeoman generator"

Is this still OKpresentation for you and if so, would I be able to give one this or next (in December) meetup? Or you are already full for this year?

**Comment by lblazecki** [comment]
Hey @slavede 
You can give it this month. Can you please send short review?

**Comment by slavede** [comment]
Hey @lblazecki , thanks! I'll create short review today/tomorrow (probably tomorrow) and send it, ok?

**Comment by lblazecki** [comment]
Great!

**Comment by slavede** [comment]
Hey @lblazecki , I guess this could be a review?

Yeoman is being used for easy scaffolding of your project. There is a ton of Yeoman generators online, but what if you don't like any of them and you want something different. Then you can create your own Yeoman generator and build on it.
I will give short introduction through slideshow/code how you can create simple Yeoman generator, publish it and make developers start using it.

Presentation will take 20-25 min, is that ok?

Let me know if you expected bigger review and I'll do so...:)

**Comment by lblazecki** [comment]
@slavede this is good! 
thank you and see you on a meetup :)
