### ISSUE TITLE
RxJS introduction

### ISSUE THREAD

**Issue by damirsehic** [jszgb/jszgb.github.io#40]
Hey, just to make is official: I'd like to give a short RxJS introduction in January. We've been using RxJS for a few months with angular 2 and also a bit on the server-side with node.

**Comment by lblazecki** [comment]
That's very interesting topic!

Not sure if we will have free spots in January. But let's be in touch.

**Comment by damirsehic** [comment]
Either that or some later date @lblazecki

**Comment by damirsehic** [comment]
@lblazecki I think you said 3rd of January so here you go.

RxJS Introduction - Reactive programming, Observables, timeless patterns and new implementations
Damir Šehić

RxJS (Reactive Extensions for JavaScript) is a library for transforming, composing, and querying streams of data. You can use it to model all kinds of data: from simple arrays of values, series of events (unfortunate or otherwise), complex flows of data, to HTTP requests. I'll try to explain what is an Observable, what is RxJS and why/where/how you can use it.

**Comment by lblazecki** [comment]
Thank you. Meetup is updated:
https://www.meetup.com/JavaScript-Zagreb/events/236663279/
