### ISSUE TITLE
Selenium + JavaScript = 😕🤔😳

### ISSUE THREAD

**Issue by zeljkofilipin** [jszgb/jszgb.github.io#43]
I would like to propose the following presentation idea: Selenium + JavaScript = 😕🤔😳

There are several Selenium bindings in JavaScript. I will compare a few of the most popular:
- [WebDriverJs](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs),
- [WebdriverIO](http://webdriver.io/),
- [Nightwatch.js](http://nightwatchjs.org/).

I can give this presentation. I'm qualified to do it because:

- I already gave this presentation at [Testival meetup #27](https://www.meetup.com/testival/events/236635146/),
- I wrote a [blog post](http://filipin.eu/selenium-javascript) about the topic,
- I have more than 10 years of experience in test automation, most of them with Selenium.

I can give the talk in Croatian or English. I need about 30 minutes to give the talk, including questions.

**Comment by dinodsaurus** [comment]
Sounds awesome to me!
Could you do this in march?

**Comment by zeljkofilipin** [comment]
If I don't already have something else, sure. Is the date/time for March already set?

**Comment by dinodsaurus** [comment]
15.3 :1st_place_medal:

**Comment by zeljkofilipin** [comment]
2017-03-15 is good for me!

**Comment by dinodsaurus** [comment]
Could you just send a PR with edits to `slides/slides.md`

**Comment by zeljkofilipin** [comment]
Done: https://github.com/jszgb/jszgb.github.io/pull/45

**Comment by dinodsaurus** [comment]
Thanks a lot!
