### ISSUE TITLE
Jest

### ISSUE THREAD

**Issue by abarisic86** [jszgb/jszgb.github.io#44]
I would like to propose a presentation about [Jest](https://facebook.github.io/jest/). It is complete JavaScript testing solution that works out of the box for any React project. I started to use it on my own projects so I can give the presentation. If somebody has more experience with it, please write your own opinion about it or things that definitely should be mentioned in presentation.

**Comment by dinodsaurus** [comment]
Do you want to do this presentation in april?

**Comment by abarisic86** [comment]
That's the plan. But, I will definitely confirm in week or so.

**Comment by dinodsaurus** [comment]
Whats your plan about this presentation? 💃

**Comment by abarisic86** [comment]
My plan was to do it next month but I guess it isn't optimal to talk about Jest two times in a row. (after Jest snapshot testing)

**Comment by dinodsaurus** [comment]
hey, do you wanna talk about jest this month?

**Comment by dinodsaurus** [comment]
Ok, I will move you to the next month @abarisic86
