### ISSUE TITLE
Blockchain with NodeJS & TypeScript

### ISSUE THREAD

**Issue by Predjo** [jszgb/jszgb.github.io#50]
Hello, I would like to propose a talk about creating a simple blockchain using NodeJS & TypeScript. I would talk about some basic concepts of the blockchain and how to create them using aforementioned technologies. I plan to make it as simple as possible so everyone can understand.

**Comment by dinodsaurus** [comment]
Can you give me a short desc of the talk?

**Comment by Predjo** [comment]
Building your own Blockchain with NodeJs & TypeScript

Everyone is talking about Blockchain these days. But do you have any idea how it works? If no, hopefully I can help you with that. And the best way to understand something is by building it yourself. We will start form the basic cryptographic functions in Node to understanding transactions, blocks, mining and the basic proof of work system.

**Comment by dinodsaurus** [comment]
It was awesome!
