### ISSUE TITLE
Styling React Components

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#52]
CSS-in-JS solutions for React, for example:

- [styled-components](https://github.com/styled-components/styled-components)
- [emotion](https://github.com/emotion-js/emotion)

**Comment by vblazenka** [comment]
@silvenon are you interested in giving a talk next year about styling solutions for React? :)

**Comment by silvenon** [comment]
I'd like to do a talk on CSS Modules + PostCSS. Someone else could do the Styled Components/Emotion one, ideally on the same day?

**Comment by vblazenka** [comment]
@silvenon great, you can create a separate issue for your talk proposal. I will close this issue and I will figure out how to handle Style Components part, maybe I will do it.
