### ISSUE TITLE
TypeScript and React - the complete solution

### ISSUE THREAD

**Issue by hbagarich** [jszgb/jszgb.github.io#53]
Hi,
I would like to propose the following presentation: TypeScript and React.
I would show the basic concepts of TypeScript and how they can be leveraged to write React components more easily. 
In the demo I would show:
- basic TypeScript concepts (classes, interfaces, enum, type checking and @types packages)
- how to setup the project and tsconfig
- how to configure webpack
- how to use tslint to enforce coding standards
- show some tip and tricks specific to TypeScript and React

How does that sound to you? :)

**Comment by vblazenka** [comment]
I would love to hear this talk! Maybe add some TS vs Flow comparison to the talk to spice it up, if there is time left for it? ;)

**Comment by dinodsaurus** [comment]
sounds good to me!

**Comment by hbagarich** [comment]
@wedranb Nice suggestion, I'll find time to include it into presentation :)

**Comment by dinodsaurus** [comment]
Do you wanna have this talk next week?

**Comment by hbagarich** [comment]
If that's an option, I'd prefer to do the talk next month as I'm a bit busy at the moment? :(

**Comment by dinodsaurus** [comment]
ok sure, then february 👍

**Comment by dinodsaurus** [comment]
Is February 21st ok @hbagarich ?

**Comment by hbagarich** [comment]
Sounds good! :)

**Comment by dinodsaurus** [comment]
could you write donw a short desc like this one - https://github.com/jszgb/jszgb.github.io/issues/57

**Comment by hbagarich** [comment]
@dinodsaurus 
Here it is:

> TypeScript has been around for some time now. With the constant monthly releases, it has come a long way. Its static typing and support for the upcoming JavaScript features makes it interesting for small projects as well as the large ones. With the @types modules, you can use almost every JavaScript library natively. It even had a first day support for the new fragments React syntax. So how does TypeScript behave with React?
I will start the talk with the demo of TypeScript basic types and features. I will show how to setup your TypeScript with React project from tsconfig to webpack, even including tslint rules. To round up the talk, I will show how we can leverage TypeScript to write robust React applications.
