### ISSUE TITLE
Introduction to React state management with MobX

### ISSUE THREAD

**Issue by anovoselnik** [jszgb/jszgb.github.io#54]
I would like to talk about MobX state management in React.
Talk outline:
- What is MobX?
- MobX concepts
- Example react app with MobX
- QA

**Comment by dinodsaurus** [comment]
Do you wanna have this talk next week?

**Comment by anovoselnik** [comment]
@dinodsaurus I can't, I am away next week, can do it next month.

**Comment by dinodsaurus** [comment]
ok, cool 👍

**Comment by dinodsaurus** [comment]
Is February 21st ok @anovoselnik ?

**Comment by anovoselnik** [comment]
Yes :) @dinodsaurus

**Comment by dinodsaurus** [comment]
Can you give some more details like this one - https://github.com/jszgb/jszgb.github.io/issues/57

**Comment by dinodsaurus** [comment]
Can we move this presentation to march?

**Comment by anovoselnik** [comment]
Ok, sure! 
Sorry for the late response.

**Comment by anovoselnik** [comment]
I will prepare the details and post them here within couple of days.

**Comment by vblazenka** [comment]
@anovoselnik Are you still interested in giving this talk?
