### ISSUE TITLE
Creating fast and type-safe React apps with Reason

### ISSUE THREAD

**Issue by vblazenka** [jszgb/jszgb.github.io#56]
Learn how to use Reason and React to write simple and fast apps while leveraging type-safe code with both the JavaScript & OCaml ecosystem.

In this presentation, I will demo simple app that I prepared and I will go through implementing a simple feature so that everyone can see the process.

Demo will show:
- Benefits of Reason
- Major differences between Reason and JavaScript
- Comparison of Flow and TypeScript versus Reason
- How to compile Reason
- How to create React app with Reason
- How to use JS packages with Reason

**Comment by silvenon** [comment]
Yesssss!

**Comment by dinodsaurus** [comment]
March!!! 🥇

**Comment by dinodsaurus** [comment]
17.4 ;)
