### ISSUE TITLE
Writing codemods with jscodeshift

### ISSUE THREAD

**Issue by silvenon** [jszgb/jszgb.github.io#57]
I would like to propose a talk about [jscodeshift](https://github.com/facebook/jscodeshift) with the following description:

> Our dependencies update quickly so frontend code often needs to be refactored to keep up. Doing this manually is manageable up to a certain point, but sometimes there is just too much code to update, and search & replace is very often not enough. This is what codemods are for—they are scripts that you can run across your files to refactor them.
>
> In my talk I'll introduce you to jscodeshift, Facebook's tool for writing codemods. Step by step you'll get familiar with JavaScript AST, I'll be extra careful to keep things at a very basic level so you can see the potential of refactoring code programmatically.

**Comment by dinodsaurus** [comment]
Wow, sounds awesome!!!
February?

**Comment by silvenon** [comment]
Yep!
