### ISSUE TITLE
Building responsive layouts for React Native

### ISSUE THREAD

**Issue by MislavMandaric** [jszgb/jszgb.github.io#61]
I would like to propose a presentation of our new open source library for building responsive React Native layouts - [React Native Responsive Layout](https://www.npmjs.com/package/react-native-responsive-layout).

We believe this library solves a real problem and that is a pain of building responsive layouts that look great both on phones and tablets, of any size and resolution. Lots of concepts we are used to on the web are not easily translated to React Native mobile development and this library bridges the gap on one of them - responsive layout.

In this talk, my colleague Sergej Jakovljev (@srolija) and I would present how to use this library, what problems does it solve and what is the benefit on using it over some other alternatives.

We think it could help React Native developers and we would like to share it first with our local community.

**Comment by dinodsaurus** [comment]
Sounds good! 💃 
This talk will be held in March 👏

**Comment by dinodsaurus** [comment]
April (17.4)?
And could you write down a short description like this - https://github.com/jszgb/jszgb.github.io/issues/57
