### ISSUE TITLE
Detox E2E testing

### ISSUE THREAD

**Issue by abarisic86** [jszgb/jszgb.github.io#62]
I would like to make a presentation about Detox. It's like they say "Gray box end to end testing framework for mobile apps.".

> Testing apps manually is possible up to a certain point. But, frequently apps grow so much that it becomes a strain on both developers and testers. More often than not, manually tested apps get pushed to stores without proper tests done. Also, on large codebases, major refactor can be a task that gets delayed or not done at all because of a cumbersome testing task ahead.
> 
> This talk won't try to convince you to write tests. Its sole purpose is to give you enough information so that if you wonder one day how you can stop losing time on manual tests, Detox is the first thing that pops into your mind.

**Comment by dinodsaurus** [comment]
Hey @abarisic86 thanks for this talk proposal! Would you like to give this talk in may? Also could you write a talk description? ;)

**Comment by vblazenka** [comment]
@abarisic86 are you still interested in giving this talk? Or should we close the issue?
