### ISSUE TITLE
React state management with Rematch

### ISSUE THREAD

**Issue by koss-lebedev** [jszgb/jszgb.github.io#67]
State management is a hot topic, with a lot of libraries trying to tackle the problem in their unique way. Redux seems to have taken a strong lead, with a huge community behind it and great documentation. But is there a way to do even better? Can we improve on Redux ideas to make developer experience better? In this talk, we’ll talk about Rematch, a state management library that strives to push Redux to the next level.

**Comment by dinodsaurus** [comment]
Thanks a lot @koss-lebedev for this talk proposal!
We currently have a summer break 🏝️ 🏄, but we will be back in September, so I propose to ping you in August with a date and more details 👍

**Comment by koss-lebedev** [comment]
thanks @dinodsaurus , that'd be awesome 👍 Talk to you then

**Comment by dinodsaurus** [comment]
Hey @koss-lebedev @zaggen , summer vacation is over  😭 , if it works for you I would propose that the meetup date should be 19th September. If it works for you that's great, if not you can make a new date proposition 😉

**Comment by koss-lebedev** [comment]
Hey @dinodsaurus ,

@Zaggen and I will be attending a different meetup on 20th of September, so, unfortunately, we won't be able to make it on 19th. Would it be possible to arrange it at a different time? We should be able to make it any day starting from the second week of October. Thanks 🙂

**Comment by dinodsaurus** [comment]
Sure, let's move it to September 12th then if it works for you 🎉

**Comment by koss-lebedev** [comment]
Awesome, 12th works! We look forward to meeting you guys 👍

**Comment by Zaggen** [comment]
Hello, @dinodsaurus, quick question at what time will the meetup start to arrange the flights 😀

**Comment by dinodsaurus** [comment]
Ohhh I forgot to share the event with you 🤦‍♂️  https://www.meetup.com/JavaScript-Zagreb/events/254140208/

**Comment by Zaggen** [comment]
Thanks a lot :)

**Comment by dinodsaurus** [comment]
Guys if you need any help, my contact is dinotrojak@gmail.com

**Comment by Zaggen** [comment]
Thanks, we are fine for now 🙂, we are staying close enough to thr venue, we'll be there in around an hour if that works for you.

**Comment by dinodsaurus** [comment]
sure, I will be there too 😉

**Comment by dinodsaurus** [comment]
Thanks for visiting us, hope to see you soon 😉  
Youtube link can be found here - https://www.youtube.com/watch?v=zswd4GmKVUE
