### ISSUE TITLE
React + Flow: Dive in

### ISSUE THREAD

**Issue by Zaggen** [jszgb/jszgb.github.io#68]
All programmers have a special part of our brains exclusively dedicated to introduce bugs in our apps, even if we don’t like to admit it, we make typos, pass wrong data and return unicorns where a number was expected. So relying on a static analysis tool like Flow to keep an eye on our code, will not only help us avoid having those issues, but more importantly by doing so we’ll look smarter. This talk will take you to some of the basics and relevance of the type system and then dive deep into typing a react app.

**Comment by dinodsaurus** [comment]
Thanks @Zaggen , like I said to @koss-lebedev , we are currently on a summer break, but I will get back to you in September 👨‍💻

**Comment by Zaggen** [comment]
@dinodsaurus sounds good, enjoy your summer break :)
