### ISSUE TITLE
Meetup with Kiwi.com speakers on Wednesday, November 14

### ISSUE THREAD

**Issue by JanBleha** [jszgb/jszgb.github.io#71]
Hello,
my name is Jan Bleha, I work as a community manager at Kiwi.com. I organize and support a lot of IT events. 

Our developers like to speak at meetups all around Europe (for example https://www.meetup.com/BarcelonaJS/events/247277405/ or https://www.meetup.com/Kyiv-ReactJS-Meetup/events/246875625/).

We want to have technical talks, mainly covering GraphQL, Relay and Serverless bringing the top JS engineers from Kiwi.com 

Therefore I would like to ask you whether you would be also interested in hosting us. 

We can help with promoting the event, get some Czech beers and pizza, maybe even help with covering the costs of some larger venue.  

We highly prefer the date of November 14, as we want to visit and speak at more meetups in the area during that week.

**Comment by dinodsaurus** [comment]
Hey Jan, thanks a lot for contacting us. Sounds awesome!! 🎉 
Will contact you back in October with more details 😃

**Comment by JanBleha** [comment]
We have the talks for the meetup on November 14 in Zagreb ready, could you create the event on meetup.com? 

[Martin Zlámal](https://github.com/mrtnzlml), Kiwi.com Senior Frontend Developer 
Talk: **5 essential tools to keep your JS apps sane and scalable**
Abstract: Keeping your JavaScript applications sane and scalable is very challenging and there are no silver-bullet tools for it. Well, actually… I am going to show you how I do it in Kiwi.com and my other projects. Get ready for 5 carefully cherry-picked tools and libraries I consider to be the key players in this heroic task. All in combination with practical tricks, tips, and recommendations from our experiences.

[Michal Sanger](https://www.linkedin.com/in/michalsanger/), Kiwi.com Principal Engineer and head of the Prague office
Talk: **Serverless backend services for JS developers**
Abstract: Everybody knows JS is for web apps. Not so many currently know JS is great for mobile apps due to React Native. And only a few know JS is a great language for backend where you don't even have to maintain a server. Do you want to build GraphQL backend, test your pull requests via headless Chrome and use all the cool JS libs and tools you already like? Pay almost zero for scalable and distributed backend service? Serverless has all of this and much more.

**Comment by vblazenka** [comment]
Thanks! We usually create the event and share it cca. two weeks before the event. That way people don't forget and more people come.
