### ISSUE TITLE
JS battle multiplayer game, RxJS, Workers and eval() ✌️

### ISSUE THREAD

**Issue by lekzd** [jszgb/jszgb.github.io#72]
Hi! I made game for coders in browser. And I want to tell you how it works.

Two players make AI code for units on JS and do battle between each other. 
Videos: 
left player: https://youtu.be/0r_gOLLxaPs 
right player: https://youtu.be/3Mmt-3FYe3U 
main screen: https://youtu.be/qv1kHNMwoxc

What are the key takeaways from this talk for the attendees? 
1. RxJS-based architecture for client and server, and state sharing based on connected client roles. 
2. Safe JS sandbox for player code without eval() 
3. Benefits of using Workers

And exactly we can make a battle between each other)

**Comment by vblazenka** [comment]
Hey, it sounds awesome. We will get back to you soon.

**Comment by vblazenka** [comment]
Hey, @lekzd how does 24th of October sounds to you? (cca. in 3 weeks) Can you make it?
If it sounds okay, take a look at our [past meetups](https://www.meetup.com/JavaScript-Zagreb/events/past/) and write up talk description so that we can put it on event page.

Thanks!

**Comment by lekzd** [comment]
Sounds very good! I will make it!

**Comment by vblazenka** [comment]
@lekzd Awesome! Post meetup description here today if possible so that I can create new event.

You can ping me on my email if you need help with anything: `blazenka.vedran@gmail.com`

**Comment by lekzd** [comment]
@wedranb 

Korotaev Aleksandr
JS battle multiplayer game, RxJS, Workers and eval() ✌️

One day I got task: make a interactive coding battle game for front-end conference. I want to tell you how to make a really safe code sandbox for JS without eval() using power of Workers. Sharing of state between clients with different roles connected using websocket. And also why reactive programming with RxJS it's much better than typical event-based programming in games. And exactly let's play in this game at the end.

**Comment by vblazenka** [comment]
Here is the event: https://www.meetup.com/JavaScript-Zagreb/events/255030109/
