### ISSUE TITLE
gRPC & protocol buffers on the web

### ISSUE THREAD

**Issue by 4nte** [jszgb/jszgb.github.io#73]
I would like to talk about gRPC & protobufs, and how it can be used to build a type-safe web API with the use of typescript. 

Presentation outline:
* introduction to gRPC & protocol buffers
* gRPC and ~~microservices~ frontend
* demo!
* QA

**Comment by vblazenka** [comment]
We will get back to you. Do you have a month on your mind when you are available to give this talk?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 4nte** [comment]
This month after 20th or anytime next month, sounds good?

**Comment by vblazenka** [comment]
First available slot is in December. If it works for you I will reserve one speaker slot for you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 4nte** [comment]
Sure, what date?

**Comment by vblazenka** [comment]
Not sure, yet. Someone will get back to you.

**Comment by vblazenka** [comment]
@antegulin can you please create a description for this talk? If you need help look at previous meetups for inspiration. [Example.](https://www.meetup.com/JavaScript-Zagreb/events/255585688/)

**Comment by dinodsaurus** [comment]
Next js event will be 12.12.2018 ;)

**Comment by 4nte** [comment]
@wedranb 
gRPC-Web: Typed Frontend Development

gRPC is a high performance & multi-platform RPC framework developed by Google. It is typically used as a communication framework for microservices, but In this talk I will show you how you can use gRPC on the frontend to achieve type-safe API's with help of typescript and protocol buffers.

**Comment by vblazenka** [comment]
Here it is: https://www.meetup.com/JavaScript-Zagreb/events/256788177/ 🎉
