### ISSUE TITLE
Firebase: The Good, the Bad and the Ugly

### ISSUE THREAD

**Issue by jamzi** [jszgb/jszgb.github.io#74]
### Talk summary

Firebase suite gives us the ability to quickly create serverless backend, add authentication, quickly deploy to a CDN and many more. Sound great, right?

Our team used Firebase extensively for the last year in a production environment and I’ll show you what we learned. We’ll explore some of its best features and also take time to talk about the bad and ugly side of the suite.

However, is Firebase really the silver bullet we all thought it was? Is it time to abandon our backend services and just use managed services that are provided? After this talk, you’ll know if Firebase is the right solution for your project.

### Who wants to hear about this presentation
Those who want to bootstrap their app with simple, maybe serverless backend and those who have tried and know Firebase.

**Comment by vblazenka** [comment]
Hey, @jamzi . Talk looks interesting. We have an open slot this December if you are up for it. We are planning the meetup on 11th or 12th. I will get back to you this week for concrete date.

**Comment by jamzi** [comment]
Yes, let's do it.
How long are the talks usually? Is there Q&A?

**Comment by vblazenka** [comment]
Great. We try to have it around 25-30min. Ideal would be 25 because people pay more attention and are not bored. Yes QA after the presentation. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vblazenka** [comment]
I can confirm that next event will be 12.12.2018. at 18:30. I will send you JS Meetup event page after we publish it.

**Comment by vblazenka** [comment]
Here it is: https://www.meetup.com/JavaScript-Zagreb/events/256788177/ 🎉
