### ISSUE TITLE
TL;DR into browser extensions

### ISSUE THREAD

**Issue by capJavert** [jszgb/jszgb.github.io#75]
## Cross browser extensions

I would like to give a talk about developing a cross browser extensions. I would talk about:

Some intro stuff:
- basic tools (SPOILER: JavaScript is used 😉)
- quickstart guide
- common pitfalls
- basic project setup
- common extension types

Kinda advanced stuff: (can be tailored to what audience is interested in)
- using advanced browser features
- managing deployment across different browser stores
- integrating extensions with your websites

I would also offer my [Clippy assistant extension](https://chrome.google.com/webstore/detail/clippy/oaknkllfdceggjpbonhiegoaifjdkfjd) as an example. [http://kickass.website/clippy](http://kickass.website/clippy)

## Who wants to hear about this presentation

Those who:
- would like to enchance their website/game/app experience with some cool quirks
- want a TL;DR into browser/web extensions development
- are interested in new ways you can interact with users on the web
- want to learn something new 😃 (obviously)

**Comment by vblazenka** [comment]
Hi, @capJavert ! Thank you for the proposal.

We have an open spot in January if you are interested? (It will be 3rd or last week of January)

**Comment by capJavert** [comment]
Hi @vblazenka , I should be able to make it. Count me in 👍

**Comment by vblazenka** [comment]
Great, I will need a short description for your talk so I can put it on the event page. Look past meetups for inspiration. [Like this](https://www.meetup.com/JavaScript-Zagreb/events/254140208/).

Please keep your presentation around 20-25min, this is a new rule we have. People sometimes extend their talks too much and nobody can follow it. So it's better to have it short and sweet with some tips they can't get from reading documentation.

Thank you! :)

**Comment by capJavert** [comment]
Cool, noted. Here is my description:

Browser extensions were a huge mess until not so long ago. Today with new WebExtensions API they are much more accessible and we can develop extensions that work inside all major browsers and share the same codebase. Other then intro into this new API, you will also hear about concepts, gotchas and ideas on how to use web extensions to enhance user experience on your website or app. Also, for old school guys, the secret guest will make a comeback.

**Comment by vblazenka** [comment]
@capJavert Hey, unfortunately we will need to postpone meetup for February. I will get back to you with a date if you are still interested. Thanks.

**Comment by capJavert** [comment]
Sure. Let me know.

**Comment by vblazenka** [comment]
I see you confirmed you are going but I will put it here: https://www.meetup.com/JavaScript-Zagreb/events/258728873/

**Comment by capJavert** [comment]
@vblazenka where should I put the slides? Slides folder in README is 404.

**Comment by vblazenka** [comment]
@capJavert Thank you for awesome talk! :)

Atm. we don't store presentations, maybe you can add presentation to slideshare? and link it here...

We plan to do the site redesign this year and we will try to figure out this better. Thanks! :)

**Comment by capJavert** [comment]
Ok gotcha, I have it here in PDF [TL;DR into browser extensions](https://drive.google.com/file/d/141GKV0ty1VlSHJ8VgzVB26_njWOqNOtC/view) .
Thanks again for the chance and see you around.  🤘
