### ISSUE TITLE
Introduction to packing and building applications with Webpack 4

### ISSUE THREAD

**Issue by antetmc2** [jszgb/jszgb.github.io#77]
Hello,
I have one web-related presentation I held not long ago at .NET meetup in Vodnjan and which was very-well received, so I am interested in holding it in Zagreb as well. I think that it would be good to hold it because it's something necessary for a lot of Web developers. I am also working a lot on it in Infobip, so I am very interested in sharing at least some of my knowledge to others. :)

Ante Tomić, Software Engineer (Infobip)

**Title**: Introduction to packing and building applications with Webpack 4

**Description**: Are you familiar with developing of applications and having to be careful to „include that script before your own because the application won't work otherwise“? Or have you ever used Webpack or something similar and ever wonder how it works? Here we will look at the basic example of how we can set up generation of our app output from no setup code to a basic example where we can look at the concepts you will need the most. We will also look into how Webpack relates to other module bundlers like Parcel or task runner like Gulp, Grunt and more.

I have materials from .NET meetup here: http://bit.ly/WebpackDotNetMeetup.

I am planning to change some things a little bit for 2nd version of presentation (and maybe change order of some stuff), but this interactive notebook is a bit more detailed version of presentation that I held. Also, presentation I held on .NET meetup was in Croatian and it was 45 minutes long, but here I would go with English version, while the presentation length is up to discussion.

**Comment by vblazenka** [comment]
Hi, sounds nice. I can add you to April meetup (we don't have an exact date yet). How does it sound? :)
Btw. we started doing max 25min presentations so keep that on mind.

**Comment by antetmc2** [comment]
Sounds good, I should be able to hold it in April :) 25 mins shouldn't be a problem

The description may be a bit different depending on which parts I'll change/shorten/remove (this description is for 45min version), but I'll send it once I'll prepare it :)

**Comment by vblazenka** [comment]
Great! :) Get back with description by the end of this month so I can create event. Cheers!

**Comment by antetmc2** [comment]
@vblazenka Here is the description: :)

*Title*: Introduction to packing and building applications with Webpack 4

*Presenter*: Ante Tomić, Software Engineer (Infobip)

*Description*: Are you familiar with developing apps and having to be careful to „include that script before your own because the application won't work“? Or have you ever used Webpack or similar solutions and wondered how they work? Here we will check out how to build the application from no setup code to the most common concepts. We will also see how Webpack relates to the other popular solutions like Parcel, Gulp or Grunt.

I didn't remove any part in the end (since all of them are important), but I simplified the description. :)

Do you maybe know when will the exact date be known?
