### ISSUE TITLE
React hooks

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#78]
Hooks got added to React in 16.8 version. They let you use state and other React features without writing a class. Im pretty sure you heard somewhere this new buzz word but is it really a buzzword or a new thing that will make our lives easier?  In this presentation we will take a dive into react functions, hooks, why are they useful and how to use them in real projects.

**Comment by dinodsaurus** [comment]
@silvenon I think you're the right guy for this job 😉

**Comment by silvenon** [comment]
Sure!

**Comment by silvenon** [comment]
The description:

> **React Hooks**
>
> I'll start by explaining how we used to solve problems like managing internal state and adding side-effects, and how we can significantly simplify our code with hooks. I'll also talk about how to correctly optimize performance and avoid common pitfalls. Finally, I'll touch on some controversies around class components and hooks.
