### ISSUE TITLE
1,2,3 Machine Learning!

### ISSUE THREAD

**Issue by capJavert** [jszgb/jszgb.github.io#83]
I would like to give a talk about Machine Learning inside native React applications.

## Summary

Machine Learning has been taboo subject forever. Is it really that complex? Well not anymore! This talk aims to show practical examples of ML features that you can develop, pitch or sell with your next application or project!

Presentation will contain many demo examples (inside React Native application) of different features that you can integrate through libraries that are ready and available to everyone (like firebase ML kit). Talk is not only developer focused and non tehnical people are also welcome to get perspective of what can be done in scope of ML concepts.

**Comment by vblazenka** [comment]
Hey @capJavert, thank you for your presentation proposal! 🎉

~Would you be interested in doing the talk this March or April?~
Would you be interested in doing this talk in the first week of April?

_Note_: We are trying to adjust meetup to be good for all speakers.

**Comment by capJavert** [comment]
I would prefer April because March looks pretty busy for me so far :)

**Comment by vblazenka** [comment]
@capJavert is first week of April okay for you? There is a possibility that the meetup will be postponed because of the coronavirus outbreak. We will need to see how the situation continues here in Zagreb. 🙏

**Comment by capJavert** [comment]
Sure, first week of April is ok.

**Comment by capJavert** [comment]
@vblazenka as I see meetups popping up again if you are still interested into the topic let me know.

**Comment by vblazenka** [comment]
@capJavert yeah, glad to hear that. We could organize something between 16.-31.6?  How is that sounding to you?

**Comment by capJavert** [comment]
@vblazenka Cool, towards the end of the month would be possible in general but when you have a concrete date we can confirm?

**Comment by vblazenka** [comment]
@capJavert hmm we could do 29.6 (Wednesday), what do you think? (or the day before/after that date)

**Comment by capJavert** [comment]
@vblazenka sounds good.

**Comment by vblazenka** [comment]
@capJavert can you let me know if the summary for the talk is still good from your POV? If not, feel free to update it or add a comment with a new description that is more to your liking. 🙇

**Comment by capJavert** [comment]
It is generic enough to still be relevant, I'll work on it some more in coming weeks and update if something major adds in.
