### ISSUE TITLE
Frontend TDD with Cypress

### ISSUE THREAD

**Issue by renatoruk** [jszgb/jszgb.github.io#84]
I'd like to give a presentation about e2e testing framework, [Cypress](https://www.cypress.io/).

Cypress is very fast in execution and has a dedicated interface with a command log which makes it ideal for test driven development. I'll show a bit of setup, methodologies and which scenarios/features would be ideal to cover with Cypress. Also, I'll showcase how it can make you more efficient and faster in code iteration.

**Comment by vblazenka** [comment]
@renatoruk Hey 👋 we are slowly starting to organize meetup again and I was wondering if you would like to talk on this topic or if you have some other ideas feel free to open a new issue and we can discuss them?

**Comment by renatoruk** [comment]
Hey @vblazenka!  👋 For the time being, I am not available for presentations due to other focuses. I'll close the issue for now and open a new one if I have something interesting.
