### ISSUE TITLE
The lazy developer guide: How to automate code updates?

### ISSUE THREAD

**Issue by antetmc2** [jszgb/jszgb.github.io#85]
_Title:_ __The lazy developer guide: How to automate code updates?__

_Description:_
How to update hundreds of projects all at once? With organizations rapidly growing, demand for the scalability of the teams grows which directly impacts projects structure and ownership. The usual dilemma is mono- vs. multi-repos, but ... What if I tell you that it does not matter much? Both approaches can punch you in the face at some point, so perhaps it is better to think bottom-up.

Today I will walk you through some of the biggest challenges that exist in both approaches and those are managing dependencies across a few hundred projects, global code updates and many other things. I will also show you examples of how we solved this inside Infobip through building our own internal libraries.

_Presenter:_ __Ante Tomić, Senior Software Engineer@Infobip__

**Comment by vblazenka** [comment]
Thanks! :) Just to confirm  6th of July (next Wednesday) works for you?
