### ISSUE TITLE
End-to-end testing made easy with Playwright

### ISSUE THREAD

**Issue by silvenon** [jszgb/jszgb.github.io#86]
I would like to give this presentation. 💪 

## Summary

We all know the benefits of end-to-end testing, but what about putting it into practice? I'll be the first one to admit that I tend to avoid it. I used to think that it was because I was lazy, incompetent or whatever, but the truth is much simpler.

I learned how to write Cypress tests, which was very useful, but even though they saved me many times I never really _liked_ writing them, so I didn't write them often enough. But when I tried Playwright, I learned that it was actually because I didn't like Cypress all that much. Playwright got me excited about end-to-end testing again! 🤩

**Comment by vblazenka** [comment]
@silvenon awesome! :) We will have pause during August and hopefully you will still be interested in giving the presentation in September or October 🤞

**Comment by vblazenka** [comment]
Hey @silvenon 👋 . Let's say summer is over and it's time to start with our meetups. 😉

I'm tinking about organizing meetup on 21st or 28th of September (so 2-3 weeks from now). Do you have a preference, how does it sound to you?

**Comment by silvenon** [comment]
21st sounds best!

**Comment by vblazenka** [comment]
@silvenon great!

**Comment by vblazenka** [comment]
@silvenon would it be possible for you to present if we move the meetup to the week after the original plan so that we do it on 27th or 28th? 🙏

**Comment by silvenon** [comment]
That's fine too 👌

**Comment by silvenon** [comment]
✅
