### ISSUE TITLE
Intro to Remix

### ISSUE THREAD

**Issue by silvenon** [jszgb/jszgb.github.io#88]
I would like to give this presentation. I've been using [Remix](https://remix.run/) quite a lot for my side projects, and I would very much like to teach it to others.

# Intro to Remix

Remix is a React framework, people often compare it to Next.js, but it has a very different goal. One of the key differences is that Remix recognizes that deployment services have advanced enough to fully embrace web standards, edge computing and full stack development. The team is geared toward teaching you better web development rather than Remix development, so the skills you learn are applicable outside of Remix as well. They support various deployment services out of the box, so you get to keep the same application code, and changing deployment targets is mostly a matter of changing one configuration value. One of their milestones is for Remix to eventually support other UI libraries as well (Vue, Svelte etc.).

**Comment by vblazenka** [comment]
Woohoo! :) 

Do you have desired month when you would like to give this talk?

**Comment by silvenon** [comment]
Nope! Whenever you think is good 👌
