### ISSUE TITLE
Write a better README

### ISSUE THREAD

**Issue by dinodsaurus** [jszgb/jszgb.github.io#9]
We need to write a better readme so it is easier for new people to contribute and join our community.
It should:
- [x] Explain the purpose of jsZgb community
- [x] For any questions please open an issue
- [x] Explain how to propose a presentation topic with `issues`
- [x] Explain how `slides` folder works
- [x] Link to our ~~gitter~~ slack channel
- [x] Link to our meetup page
- [x]  Add [code of conduct](https://github.com/nodeschool/berlin/blob/master/codeofconduct.md)
- [x] Links for other development user groups
- [ ] Add a transparent budget.md file (if needed)???

**Comment by dinodsaurus** [comment]
@shime could you do this one ?

**Comment by dinodsaurus** [comment]
This looks nice on first, but we could add some more badges(slack, twitter etc) and text (how to add an issue, how to contribute to our community) I think @silvenon can do some magic on this one :D

**Comment by silvenon** [comment]
Sure!
